
package com.company;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Vanzari extends javax.swing.JPanel {
    public static String codProdus;
    public static String cid = "0";
    public static int cant_total=0;
    public static int nrf = 001;

    public void cal_total_pret(){
        double cant = Double.valueOf(prod_cant.getText());
        double unit_pret = Double.valueOf(u_pret.getText());
        double total = cant * unit_pret;
        
        t_pret.setText(String.valueOf(total));
    }
    public Vanzari() {
        initComponents();
        data_load();
        
    }
    
    public void data_load(){
        try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM clienti");
            Vector v = new Vector();
            
            while(rs.next()){
                v.add(rs.getString("c_nume"));
                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                client_combo.setModel(com);
            }  
        } catch (SQLException e) {
            System.out.println(e);
        }
        
                try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM produse");
            Vector v = new Vector();
            
            while(rs.next()){
                v.add(rs.getString("p_nume"));
                DefaultComboBoxModel com = new DefaultComboBoxModel(v);
                prod_combo.setModel(com);
            }  
        } catch (SQLException e) {
            System.out.println(e);
        }
                
        //preia nr factura        
                try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT fact_nr FROM facturi");

            while (rs.next()){
                nrf = Integer.valueOf(rs.getString("fact_nr"));
                nrf++;
                nr_factura.setText(String.valueOf(nrf));
            }
                  
            
        } catch (SQLException e) {
                    System.out.println(e);
        }
        
    }
    
    public void calcTotalFactura(){
        int randuri = jTable1.getRowCount();
        double total=0;
        
        for (int i = 0; i < randuri; i++) {
            total += Double.valueOf(jTable1.getValueAt(i, 5).toString());
        }
        total_factura.setText(String.valueOf(total));
    }
    
    public void calRest(){
        double sumaPlatita = Double.valueOf(suma_platita.getText());
        double totalFactura = Double.valueOf(total_factura.getText());
        double diferenta = totalFactura - sumaPlatita;
        restDePlata.setText(String.valueOf(diferenta));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nr_factura = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        client_combo = new javax.swing.JComboBox<>();
        prod_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        prod_cant = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        u_pret = new javax.swing.JLabel();
        t_pret = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cod_produs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        adauga_cos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        suma_platita = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        total_factura = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        restDePlata = new javax.swing.JTextField();
        plateste = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Nr. factura:");

        nr_factura.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nr_factura.setText("001");
        nr_factura.setMaximumSize(new java.awt.Dimension(11, 24));
        nr_factura.setMinimumSize(new java.awt.Dimension(11, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nr_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nr_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Client:");

        client_combo.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        client_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_comboActionPerformed(evt);
            }
        });

        prod_combo.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        prod_combo.setSelectedIndex(-1);
        prod_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prod_comboActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Produs:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Cantitate:");

        prod_cant.setText("1");
        prod_cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prod_cantKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Pret:");

        u_pret.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        u_pret.setText("00.00");

        t_pret.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        t_pret.setText("00.00");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("Pret total:");

        cod_produs.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cod_produs.setPreferredSize(new java.awt.Dimension(66, 17));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(client_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prod_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prod_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(u_pret, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pret, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cod_produs, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cod_produs, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(t_pret)
                    .addComponent(u_pret)
                    .addComponent(jLabel6)
                    .addComponent(prod_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(prod_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(client_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr. factura", "Nume", "Cod produs", "Cantitate", "Pret", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adauga_cos.setText("Adauga in cos");
        adauga_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adauga_cosActionPerformed(evt);
            }
        });

        jButton2.setText("Sterge");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sterge tot");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adauga_cos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(adauga_cos)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Suma platita:");

        suma_platita.setText("00.00");
        suma_platita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                suma_platitaKeyReleased(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Suma totala:");

        total_factura.setText("00.00");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Rest de plata:");

        restDePlata.setText("00.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restDePlata, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(total_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(restDePlata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(suma_platita, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(suma_platita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        plateste.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        plateste.setText("Plateste si Printeaza");
        plateste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(plateste)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plateste)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            int rw = jTable1.getSelectedRow();
            String id = dt.getValueAt(rw, 0).toString();
            dt.removeRow(rw);
            calcTotalFactura();
            calRest();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void prod_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prod_comboActionPerformed
        
        String nume = prod_combo.getSelectedItem().toString();
        try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT p_pret,p_cod FROM produse WHERE p_nume='"+nume+"' ");
            
            if(rs.next()){
                u_pret.setText(rs.getString("p_pret"));
                codProdus =rs.getString("p_cod");
                cod_produs.setText(codProdus);
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        cal_total_pret();
        calRest();

        

    }//GEN-LAST:event_prod_comboActionPerformed

    private void prod_cantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prod_cantKeyReleased
        cal_total_pret();
        calRest();
    }//GEN-LAST:event_prod_cantKeyReleased

    private void adauga_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adauga_cosActionPerformed
        //verific daca a fost selectat produs
        if (prod_combo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Alege un produs");
        } else {

        //adaugare produse in cos
        
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        Vector v = new Vector();
        
        v.add(nr_factura.getText().toString());
        v.add(prod_combo.getSelectedItem().toString());
        v.add(codProdus); //cod de bare
        v.add(prod_cant.getText());
        v.add(u_pret.getText());
        v.add(t_pret.getText());
        
        dt.addRow(v);
        calcTotalFactura();
        calRest();
        }
    }//GEN-LAST:event_adauga_cosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);
            calcTotalFactura();
            calRest();
            client_combo.setEnabled(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void suma_platitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suma_platitaKeyReleased
        calRest();
    }//GEN-LAST:event_suma_platitaKeyReleased

    private void platesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platesteActionPerformed
        //trimite factura in bd
        DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
        int randuri = jTable1.getRowCount();
        
        
        try {
        Statement s = db.mycon().createStatement();
        
            for (int i = 0; i < randuri; i++) {
                String nrFact = jTable1.getValueAt(i, 0).toString();
                String numeP = jTable1.getValueAt(i, 1).toString();
                String codP = jTable1.getValueAt(i, 2).toString();
                String cant = jTable1.getValueAt(i, 3).toString();
                String pretU = jTable1.getValueAt(i, 4).toString();
                String pretTotal = jTable1.getValueAt(i, 5).toString();
                cant_total += Integer.parseInt(cant);
                //update vanzari
                s.executeUpdate("INSERT INTO vanzari (nr_fact,nume_p,cod_p,cant,pret_u,pret_t) VALUES ('"+nrFact+"','"+numeP+"','"+codP+"','"+cant+"','"+pretU+"','"+pretTotal+"') ");
            
            }
        JOptionPane.showMessageDialog(null, "Datele au fost salvate");

        } catch (SQLException ex) {
                System.out.println(ex);
            }
        
        try {
            //update facturi `fact_nr`, `cid`, `nume_client`, `total_cant`, `total_valoare`, `status`, `rest`
            int nrFact = Integer.parseInt(nr_factura.getText());
            String numeClient = client_combo.getSelectedItem().toString();
            String totalValoare = total_factura.getText().toString();
            String rest = restDePlata.getText().toString();
            int cl_id = Integer.parseInt(cid);
            String cantTotalafromInt = String.valueOf(cant_total);
            //verific daca fac este platita
           double total =Double.valueOf(totalValoare);
           double restd = Double.valueOf(rest);
           String status = null;
            if (total==restd) {
                status = "neachitat";
            } else if (restd==0){
                status = "achitat";
            } else {
                status = "partial";
            }
            Statement s = db.mycon().createStatement();
            s.executeUpdate("INSERT INTO facturi (fact_nr, cid, nume_client, total_cant, total_valoare, status, rest) VALUES ('"+nrFact+"','"+cl_id+"','"+numeClient+"','"+cantTotalafromInt+"','"+totalValoare+"','"+status+"','"+rest+"') ");

                
        } catch (NumberFormatException | SQLException e) {
            System.out.println(e);
        }
        

    }//GEN-LAST:event_platesteActionPerformed

    private void client_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_comboActionPerformed
        //daca tabelul este gol, poti selecta
//        if(jTable1.getRowCount() == 0){
//            client_combo.setEnabled(false);
//        }
        //daca tabelul are cel putin o linie, poti selecta doar acelasi client
        
        String nume = client_combo.getSelectedItem().toString();
        try {
            Statement s = db.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT cid,c_nume FROM clienti WHERE c_nume='"+nume+"' ");
            
            if(rs.next()){
                cid = rs.getString("cid");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        cal_total_pret();
        calRest();
    }//GEN-LAST:event_client_comboActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adauga_cos;
    private javax.swing.JComboBox<String> client_combo;
    private javax.swing.JLabel cod_produs;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nr_factura;
    private javax.swing.JButton plateste;
    private javax.swing.JTextField prod_cant;
    private javax.swing.JComboBox<String> prod_combo;
    private javax.swing.JTextField restDePlata;
    private javax.swing.JTextField suma_platita;
    private javax.swing.JLabel t_pret;
    private javax.swing.JTextField total_factura;
    private javax.swing.JLabel u_pret;
    // End of variables declaration//GEN-END:variables
}
